In [1]:
import sqlite3 as sq
import pandas as pd

In [2]:
# Load the 2025 Chicago crime dataset, inspect the first few rows, and check column names
crime = pd.read_csv("chicago_crime_2025.csv")
crime.head()
crime.columns

Index(['id', 'case_number', 'date', 'block', 'iucr', 'primary_type',
       'description', 'location_description', 'arrest', 'domestic', 'beat',
       'district', 'ward', 'community_area', 'fbi_code', 'x_coordinate',
       'y_coordinate', 'year', 'updated_on', 'latitude', 'longitude',
       'location'],
      dtype='str')

In [3]:
# Convert 'date' column to datetime
crime["date"] = pd.to_datetime(crime["date"])

# Extract hour and month into new columns
crime["hour"] = crime["date"].dt.hour
crime["month"] = crime["date"].dt.month

# Establish a connection to a SQLite database
conn = sq.connect("crime.db")

In [4]:
# Save the Pandas DataFrame to the SQLite database as table "chicago_crime_2025",
# replacing the table if it already exists and excluding the DataFrame index
crime.to_sql("chicago_crime_2025",conn,if_exists="replace",index=False)

236633

**Query 1 - Window function: rank crime types by frequency**

In [5]:
query = """SELECT primary_type,
       COUNT(*) AS crime_count,
       RANK() OVER (ORDER BY COUNT(*) DESC) AS crime_rank
FROM chicago_crime_2025
GROUP BY primary_type;"""

output = pd.read_sql(query, conn) 
output

                         primary_type  crime_count  crime_rank
0                               THEFT        55040           1
1                             BATTERY        42538           2
2                     CRIMINAL DAMAGE        26205           3
3                             ASSAULT        21559           4
4                 MOTOR VEHICLE THEFT        17232           5
5                       OTHER OFFENSE        16742           6
6                  DECEPTIVE PRACTICE        14740           7
7                            BURGLARY         9710           8
8                           NARCOTICS         7417           9
9                             ROBBERY         5816          10
10                  WEAPONS VIOLATION         5444          11
11                  CRIMINAL TRESPASS         5322          12
12            CRIMINAL SEXUAL ASSAULT         1672          13
13         OFFENSE INVOLVING CHILDREN         1541          14
14                        SEX OFFENSE         1309          15
15             PUBLIC PEACE VIOLATION         1056          16
16   INTERFERENCE WITH PUBLIC OFFICER          915          17
17                           STALKING          572          18
18                           HOMICIDE          426          19
19                              ARSON          373          20
20  CONCEALED CARRY LICENSE VIOLATION          277          21
21               LIQUOR LAW VIOLATION          200          22
22                       PROSTITUTION          189          23
23                       INTIMIDATION          143          24
24                         KIDNAPPING           89          25
25                          OBSCENITY           55          26
26                  HUMAN TRAFFICKING           15          27
27                           GAMBLING           13          28
28                   PUBLIC INDECENCY           10          29
29           OTHER NARCOTIC VIOLATION           10          29
30                       NON-CRIMINAL            3          31

**Query 2 - JOIN: Crime totals with arrest rates**

In [6]:
query = """SELECT c.primary_type,
       c.crime_count,
       a.arrest_rate
FROM
    (SELECT primary_type, COUNT(*) AS crime_count
     FROM chicago_crime_2025
     GROUP BY primary_type) c
JOIN
    (SELECT primary_type, AVG(arrest) AS arrest_rate
     FROM chicago_crime_2025
     GROUP BY primary_type) a
ON c.primary_type = a.primary_type
ORDER BY c.crime_count DESC;"""

output = pd.read_sql(query, conn) 
output

                         primary_type  crime_count  arrest_rate
0                               THEFT        55040     0.089499
1                             BATTERY        42538     0.190700
2                     CRIMINAL DAMAGE        26205     0.043122
3                             ASSAULT        21559     0.124171
4                 MOTOR VEHICLE THEFT        17232     0.033658
5                       OTHER OFFENSE        16742     0.202365
6                  DECEPTIVE PRACTICE        14740     0.030258
7                            BURGLARY         9710     0.047271
8                           NARCOTICS         7417     0.948092
9                             ROBBERY         5816     0.094051
10                  WEAPONS VIOLATION         5444     0.779390
11                  CRIMINAL TRESPASS         5322     0.315483
12            CRIMINAL SEXUAL ASSAULT         1672     0.029306
13         OFFENSE INVOLVING CHILDREN         1541     0.070084
14                        SEX OFFENSE         1309     0.082506
15             PUBLIC PEACE VIOLATION         1056     0.506629
16   INTERFERENCE WITH PUBLIC OFFICER          915     0.915847
17                           STALKING          572     0.041958
18                           HOMICIDE          426     0.328638
19                              ARSON          373     0.117962
20  CONCEALED CARRY LICENSE VIOLATION          277     0.974729
21               LIQUOR LAW VIOLATION          200     0.930000
22                       PROSTITUTION          189     0.910053
23                       INTIMIDATION          143     0.020979
24                         KIDNAPPING           89     0.078652
25                          OBSCENITY           55     0.509091
26                  HUMAN TRAFFICKING           15     0.066667
27                           GAMBLING           13     0.923077
28           OTHER NARCOTIC VIOLATION           10     0.500000
29                   PUBLIC INDECENCY           10     1.000000
30                       NON-CRIMINAL            3     1.000000

**Query 3 - Crime counts by month for 2025**

In [7]:
query = """SELECT month, COUNT(*) AS crime_count
FROM chicago_crime_2025
GROUP BY month
ORDER BY crime_count DESC;"""

output = pd.read_sql(query, conn) 
output

    month  crime_count
0       7        22624
1       8        21273
2       6        21092
3      10        20898
4       5        20459
5       9        20283
6       3        19741
7       4        19617
8       1        18487
9      11        18312
10     12        17332
11      2        16515