In [4]:
import sqlite3 as sq
import pandas as pd

In [ ]:
# 2025 Chicago crime dataset
crime = pd.read_csv("chicago_crime_2025.csv")
crime.head()
crime.columns

Index(['id', 'case_number', 'date', 'block', 'iucr', 'primary_type',
       'description', 'location_description', 'arrest', 'domestic', 'beat',
       'district', 'ward', 'community_area', 'fbi_code', 'x_coordinate',
       'y_coordinate', 'year', 'updated_on', 'latitude', 'longitude',
       'location'],
      dtype='object')

In [ ]:
# Convert to datetime
crime["date"] = pd.to_datetime(crime["date"])

# Extract hour and month 
crime["hour"] = crime["date"].dt.hour
crime["month"] = crime["date"].dt.month

# SQLite database
conn = sq.connect("crime.db")

In [ ]:
# Save to the SQLite database as "chicago_crime_2025",
crime.to_sql("chicago_crime_2025",conn,if_exists="replace",index=False)

236633

**Query 1 - Window function: rank crime types by frequency**

In [8]:
query = """SELECT primary_type,
       COUNT(*) AS crime_count,
       RANK() OVER (ORDER BY COUNT(*) DESC) AS crime_rank
FROM chicago_crime_2025
GROUP BY primary_type;"""

output = pd.read_sql(query, conn) 
output

                         primary_type  crime_count  crime_rank
0                               THEFT        55040           1
1                             BATTERY        42538           2
2                     CRIMINAL DAMAGE        26205           3
3                             ASSAULT        21559           4
4                 MOTOR VEHICLE THEFT        17232           5
5                       OTHER OFFENSE        16742           6
6                  DECEPTIVE PRACTICE        14740           7
7                            BURGLARY         9710           8
8                           NARCOTICS         7417           9
9                             ROBBERY         5816          10
10                  WEAPONS VIOLATION         5444          11
11                  CRIMINAL TRESPASS         5322          12
12            CRIMINAL SEXUAL ASSAULT         1672          13
13         OFFENSE INVOLVING CHILDREN         1541          14
14                        SEX OFFENSE         1309          15
15             PUBLIC PEACE VIOLATION         1056          16
16   INTERFERENCE WITH PUBLIC OFFICER          915          17
17                           STALKING          572          18
18                           HOMICIDE          426          19
19                              ARSON          373          20
20  CONCEALED CARRY LICENSE VIOLATION          277          21
21               LIQUOR LAW VIOLATION          200          22
22                       PROSTITUTION          189          23
23                       INTIMIDATION          143          24
24                         KIDNAPPING           89          25
25                          OBSCENITY           55          26
26                  HUMAN TRAFFICKING           15          27
27                           GAMBLING           13          28
28                   PUBLIC INDECENCY           10          29
29           OTHER NARCOTIC VIOLATION           10          29
30                       NON-CRIMINAL            3          31

**Query 2 - JOIN: Crime totals with arrest rates**

In [9]:
query = """SELECT c.primary_type,
       c.crime_count,
       a.arrest_rate
FROM
    (SELECT primary_type, COUNT(*) AS crime_count
     FROM chicago_crime_2025
     GROUP BY primary_type) c
JOIN
    (SELECT primary_type, AVG(arrest) AS arrest_rate
     FROM chicago_crime_2025
     GROUP BY primary_type) a
ON c.primary_type = a.primary_type
ORDER BY c.crime_count DESC;"""

output = pd.read_sql(query, conn) 
output

                         primary_type  crime_count  arrest_rate
0                               THEFT        55040     0.089499
1                             BATTERY        42538     0.190700
2                     CRIMINAL DAMAGE        26205     0.043122
3                             ASSAULT        21559     0.124171
4                 MOTOR VEHICLE THEFT        17232     0.033658
5                       OTHER OFFENSE        16742     0.202365
6                  DECEPTIVE PRACTICE        14740     0.030258
7                            BURGLARY         9710     0.047271
8                           NARCOTICS         7417     0.948092
9                             ROBBERY         5816     0.094051
10                  WEAPONS VIOLATION         5444     0.779390
11                  CRIMINAL TRESPASS         5322     0.315483
12            CRIMINAL SEXUAL ASSAULT         1672     0.029306
13         OFFENSE INVOLVING CHILDREN         1541     0.070084
14                        SEX OFFENSE         1309     0.082506
15             PUBLIC PEACE VIOLATION         1056     0.506629
16   INTERFERENCE WITH PUBLIC OFFICER          915     0.915847
17                           STALKING          572     0.041958
18                           HOMICIDE          426     0.328638
19                              ARSON          373     0.117962
20  CONCEALED CARRY LICENSE VIOLATION          277     0.974729
21               LIQUOR LAW VIOLATION          200     0.930000
22                       PROSTITUTION          189     0.910053
23                       INTIMIDATION          143     0.020979
24                         KIDNAPPING           89     0.078652
25                          OBSCENITY           55     0.509091
26                  HUMAN TRAFFICKING           15     0.066667
27                           GAMBLING           13     0.923077
28           OTHER NARCOTIC VIOLATION           10     0.500000
29                   PUBLIC INDECENCY           10     1.000000
30                       NON-CRIMINAL            3     1.000000

**Query 3 - Crime counts by month for 2025**

In [10]:
query = """SELECT month, COUNT(*) AS crime_count
FROM chicago_crime_2025
GROUP BY month
ORDER BY crime_count DESC;"""

output = pd.read_sql(query, conn) 
output

    month  crime_count
0       7        22624
1       8        21273
2       6        21092
3      10        20898
4       5        20459
5       9        20283
6       3        19741
7       4        19617
8       1        18487
9      11        18312
10     12        17332
11      2        16515

Query 4: JOIN crime counts with arrest rates by district

In [11]:
query = """
SELECT
    c.district,
    c.total_crimes,
    a.total_arrests,
    a.arrest_rate
FROM
    (
        SELECT
            district,
            COUNT(*) AS total_crimes
        FROM chicago_crime_2025
        WHERE district IS NOT NULL
        GROUP BY district
    ) c
JOIN
    (
        SELECT
            district,
            SUM(CASE WHEN arrest = 1 THEN 1 ELSE 0 END) AS total_arrests,
            ROUND(AVG(arrest), 4) AS arrest_rate
        FROM chicago_crime_2025
        WHERE district IS NOT NULL
        GROUP BY district
    ) a
ON c.district = a.district
ORDER BY a.arrest_rate DESC, c.total_crimes DESC;
"""

output = pd.read_sql(query, conn)
output

    district  total_crimes  total_arrests  arrest_rate
0         11         12926           3913       0.3027
1         10          9497           2487       0.2619
2         25         11534           2245       0.1946
3          7         10105           1939       0.1919
4          1         13670           2516       0.1841
5         15          7812           1437       0.1839
6          5          9272           1646       0.1775
7         31            12              2       0.1667
8         16          8069           1296       0.1606
9          9         10464           1658       0.1584
10         8         15197           2321       0.1527
11        17          7289           1112       0.1526
12         3         12710           1878       0.1478
13        24          7594           1122       0.1477
14        14          8015           1176       0.1467
15         6         13557           1944       0.1434
16        18         13188           1772       0.1344
17        22          7614            994       0.1305
18         4         13063           1657       0.1268
19        20          4984            605       0.1214
20         2         12680           1370       0.1080
21        12         14882           1472       0.0989
22        19         12499           1200       0.0960

Query 5: WINDOW FUNCTION rank districts by arrest rate

In [13]:
query = """
SELECT
    district,
    COUNT(*) AS total_crimes,
    ROUND(AVG(arrest), 4) AS arrest_rate,
    RANK() OVER (ORDER BY AVG(arrest) DESC) AS arrest_rate_rank
FROM chicago_crime_2025
WHERE district IS NOT NULL
GROUP BY district
ORDER BY arrest_rate_rank;
"""

output = pd.read_sql(query, conn)
output

    district  total_crimes  arrest_rate  arrest_rate_rank
0         11         12926       0.3027                 1
1         10          9497       0.2619                 2
2         25         11534       0.1946                 3
3          7         10105       0.1919                 4
4          1         13670       0.1841                 5
5         15          7812       0.1839                 6
6          5          9272       0.1775                 7
7         31            12       0.1667                 8
8         16          8069       0.1606                 9
9          9         10464       0.1584                10
10         8         15197       0.1527                11
11        17          7289       0.1526                12
12         3         12710       0.1478                13
13        24          7594       0.1477                14
14        14          8015       0.1467                15
15         6         13557       0.1434                16
16        18         13188       0.1344                17
17        22          7614       0.1305                18
18         4         13063       0.1268                19
19        20          4984       0.1214                20
20         2         12680       0.1080                21
21        12         14882       0.0989                22
22        19         12499       0.0960                23

Query 6: SUBQUERY + JOIN for crime type and domestic status

In [14]:
query = """
SELECT
    x.primary_type,
    x.domestic,
    x.total_crimes,
    y.arrest_rate
FROM
    (
        SELECT
            primary_type,
            domestic,
            COUNT(*) AS total_crimes
        FROM chicago_crime_2025
        GROUP BY primary_type, domestic
        HAVING COUNT(*) >= 50
    ) x
JOIN
    (
        SELECT
            primary_type,
            domestic,
            ROUND(AVG(arrest), 4) AS arrest_rate
        FROM chicago_crime_2025
        GROUP BY primary_type, domestic
    ) y
ON x.primary_type = y.primary_type
AND x.domestic = y.domestic
ORDER BY y.arrest_rate DESC, x.total_crimes DESC;
"""

output = pd.read_sql(query, conn)
output

                         primary_type  domestic  total_crimes  arrest_rate
0   CONCEALED CARRY LICENSE VIOLATION         0           277       0.9747
1                           NARCOTICS         0          7406       0.9484
2                LIQUOR LAW VIOLATION         0           200       0.9300
3    INTERFERENCE WITH PUBLIC OFFICER         0           894       0.9161
4                        PROSTITUTION         0           189       0.9101
5                   WEAPONS VIOLATION         0          5380       0.7796
6                   WEAPONS VIOLATION         1            64       0.7656
7                            HOMICIDE         1            50       0.7400
8              PUBLIC PEACE VIOLATION         0          1023       0.5161
9                   CRIMINAL TRESPASS         0          4918       0.3255
10                           HOMICIDE         0           376       0.2739
11                      OTHER OFFENSE         0         10769       0.2470
12                            BATTERY         1         22589       0.2145
13                  CRIMINAL TRESPASS         1           404       0.1931
14                            BATTERY         0         19949       0.1637
15                            ASSAULT         1          6164       0.1413
16                         KIDNAPPING         0            57       0.1228
17                      OTHER OFFENSE         1          5973       0.1219
18                           BURGLARY         1           309       0.1197
19                            ASSAULT         0         15395       0.1173
20                              ARSON         0           343       0.1166
21                        SEX OFFENSE         0          1006       0.1004
22                            ROBBERY         0          5607       0.0947
23                MOTOR VEHICLE THEFT         1           366       0.0929
24                              THEFT         0         52221       0.0921
25                    CRIMINAL DAMAGE         1          3648       0.0866
26            CRIMINAL SEXUAL ASSAULT         1           341       0.0792
27                            ROBBERY         1           209       0.0766
28         OFFENSE INVOLVING CHILDREN         0           380       0.0737
29         OFFENSE INVOLVING CHILDREN         1          1161       0.0689
30                           STALKING         1           272       0.0478
31                           BURGLARY         0          9401       0.0449
32                              THEFT         1          2819       0.0419
33                           STALKING         0           300       0.0367
34                    CRIMINAL DAMAGE         0         22557       0.0361
35                MOTOR VEHICLE THEFT         0         16866       0.0324
36                 DECEPTIVE PRACTICE         0         14499       0.0304
37                       INTIMIDATION         0           119       0.0252
38                        SEX OFFENSE         1           303       0.0231
39                 DECEPTIVE PRACTICE         1           241       0.0207
40            CRIMINAL SEXUAL ASSAULT         0          1331       0.0165

Summary statement on query 4-6 written by Naeliz:

These SQL results reinforce the modeling section by showing that arrest outcomes vary across both geography and offense context. District level queries show differences in arrest rates, with some districts such as 11 and 10 having notably higher arrest shares than others. This suggests that district is a relevant predictor. The crime-type-by-domestic query adds support for the models by showing that arrest likelihood changes across offense categories and domestic status, with offenses like narcotics and weapons violations having much higher arrest rates than crimes such as theft, criminal damage, and motor vehicle theft.